In [1]:
# Import
import pandas as pd
import json
import csv

In [2]:
# Read File
deal = pd.read_csv('../Resources/Final Deal.csv', low_memory=False)
deal = pd.DataFrame(deal)
deal.head()

,City,HouseName,District,TotalPrice,Price,Floor,Square,ConstructionTime,Bedrooms,LivingRooms,...,Type,Structure,Renovation,Elevator,Subway,TradeTime,DaysonMarket,Followers,Lng,Lat
0,Beijing,,7,4150000.0,31680.0,High,131.00,2005,2.0,2.0,...,Tower,Steel/Concrete,Simplicity,Yes,Yes,2016,1464,106,116.475489,40.019520
1,Beijing,,7,5750000.0,43436.0,High,132.38,2004,2.0,2.0,...,Tower,Steel/Concrete,HardCover,Yes,No,2016,903,126,116.453917,39.881534
2,Beijing,,7,10300000.0,52021.0,Middle,198.00,2005,3.0,3.0,...,Plate,Steel/Concrete,Simplicity,Yes,No,2016,1271,48,116.561978,39.877145
3,Beijing,,6,2970000.0,22202.0,Low,134.00,2008,3.0,3.0,...,Tower,Steel/Concrete,Other,Yes,No,2016,965,138,116.438010,40.076114
4,Beijing,,1,3920000.0,48396.0,Middle,81.00,1960,2.0,2.0,...,Plate,Mixed,Rough,No,Yes,2016,927,286,116.428392,39.886229

In [3]:
# Funtion 
def csv_to_json(csvFilePath, jsonFilePath):
    jsonArray = []
      
    #read csv file
    with open(csvFilePath, encoding='utf-8') as csvf: 
        #load csv file data using csv library's dictionary reader
        csvReader = csv.DictReader(csvf) 

        #convert each csv row into python dict
        for row in csvReader: 
            #add this python dict to json array
            jsonArray.append(row)
  
    #convert python jsonArray to JSON String and write to file
    with open(jsonFilePath, 'w', encoding='utf-8') as jsonf: 
        jsonString = json.dumps(jsonArray,ensure_ascii=False, indent=4)
        jsonf.write(jsonString)

In [4]:
len(deal)

162327

In [5]:
deal = deal.drop(labels=range(5000,159000),axis=0)

In [6]:
len(deal)

8327

In [7]:
deal.head()

,City,HouseName,District,TotalPrice,Price,Floor,Square,ConstructionTime,Bedrooms,LivingRooms,...,Type,Structure,Renovation,Elevator,Subway,TradeTime,DaysonMarket,Followers,Lng,Lat
0,Beijing,,7,4150000.0,31680.0,High,131.00,2005,2.0,2.0,...,Tower,Steel/Concrete,Simplicity,Yes,Yes,2016,1464,106,116.475489,40.019520
1,Beijing,,7,5750000.0,43436.0,High,132.38,2004,2.0,2.0,...,Tower,Steel/Concrete,HardCover,Yes,No,2016,903,126,116.453917,39.881534
2,Beijing,,7,10300000.0,52021.0,Middle,198.00,2005,3.0,3.0,...,Plate,Steel/Concrete,Simplicity,Yes,No,2016,1271,48,116.561978,39.877145
3,Beijing,,6,2970000.0,22202.0,Low,134.00,2008,3.0,3.0,...,Tower,Steel/Concrete,Other,Yes,No,2016,965,138,116.438010,40.076114
4,Beijing,,1,3920000.0,48396.0,Middle,81.00,1960,2.0,2.0,...,Plate,Mixed,Rough,No,Yes,2016,927,286,116.428392,39.886229

In [8]:
deal.to_csv('../Resources/Deal_html.csv', index=False)

In [9]:
# Deal.json
csvFilePath = '../Resources/Deal_html.csv'
jsonFilePath = '../Resources/Final Deal_html.json'
csv_to_json(csvFilePath, jsonFilePath)